# Generated by Django 4.0.5 on 2022-12-14 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_att', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 14)),
        ),
        migrations.AddField(
            model_name='articles',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
