# Generated by Django 4.0.5 on 2022-12-14 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_att', '0002_articles_date_articles_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 17, 46, 13, 893839, tzinfo=utc)),
        ),
    ]
