# Generated by Django 4.0.5 on 2022-12-15 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_att', '0005_alter_articles_date_alter_articles_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 10, 38, 4, 900718, tzinfo=utc)),
        ),
    ]
