# Generated by Django 4.0.5 on 2022-12-15 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_att', '0006_alter_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 11, 48, 57, 268014, tzinfo=utc)),
        ),
    ]
